# Generated by Django 2.2.13 on 2021-02-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210224_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('curso_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_asignado_estudiante', to='api.Asignacion_Curso')),
                ('estudiante', models.ManyToManyField(related_name='estudiante', to='api.Estudiante')),
            ],
        ),
        migrations.AlterField(
            model_name='detalle_curso',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='Portada'),
        ),
        migrations.DeleteModel(
            name='Asignacion_Curso_Est',
        ),
    ]
