# Generated by Django 2.2.13 on 2021-02-24 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210224_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion_estudiante',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='asignacion_estudiante',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='api.Estudiante'),
        ),
    ]
