# Generated by Django 2.2.13 on 2021-03-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210224_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_curso',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
