# Generated by Django 2.2.13 on 2021-03-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_detalle_curso_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='nombre_evento',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
