# Generated by Django 2.2.13 on 2021-03-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tarea_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_curso',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='Portadas_Curso'),
        ),
    ]
