# Generated by Django 2.2.13 on 2021-03-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210308_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion_tarea',
            name='descripcion',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='calificacion_tarea',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos_tarea'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grado_estudiante', to='api.Grado'),
        ),
    ]
