# Generated by Django 2.2.13 on 2021-03-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210311_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grado_estudiante', to='api.Grado'),
        ),
    ]
