# Generated by Django 2.2.13 on 2021-03-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tarea_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='catedratico',
            name='inicio_sesion',
            field=models.BooleanField(default=False),
        ),
    ]
