# Generated by Django 2.2.13 on 2021-03-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_catedratico_inicio_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='inicio_sesion',
            field=models.BooleanField(default=False),
        ),
    ]
