# Generated by Django 2.2.13 on 2021-03-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210322_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inicio_sesion',
            field=models.BooleanField(default=False),
        ),
    ]
