# Generated by Django 2.2.13 on 2021-03-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_profile_inicio_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo_escolar',
            name='titular',
            field=models.BooleanField(default=True),
        ),
    ]
