# Generated by Django 2.2.13 on 2021-03-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_ciclo_escolar_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo_escolar',
            name='titular',
            field=models.BooleanField(),
        ),
    ]
