from .profile import Profile
from .asignacion_curso import Asignacion_Curso
from .asignacion_estudiante import Asignacion_Estudiante
from .catedratico import Catedratico
from .estudiante import Estudiante
from .grado import Grado
from .seccion import Seccion
from .tarea import Tarea
from .profesion import Profesion
from .curso import Curso
from .detalle_curso import Detalle_Curso
from .evento import Evento
from .nivel import Nivel
from .calificacion_tarea import Calificacion_Tarea
from .ciclo_escolar import Ciclo_Escolar
from .rol import Rol
